name: Python Fruits Check

on:
  push:
    branches: [ main ]

jobs:
  run-python-file:
    runs-on: ubuntu-latest

    steps:
      - name: Get repository code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Run fruits.py
        run: python fruits.py